bundler_args: --without development doc
env:
  global:
    - JRUBY_OPTS="$JRUBY_OPTS --debug"
language: ruby
rvm:
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3.0
  - jruby-9.0.0.0
  - jruby-9.0.1.0
  - jruby-head
  - ruby-head
  - rbx-2
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
    - rvm: rbx-2
  fast_finish: true
sudo: false
